markdown: kramdown
permalink: /blog/:year/:title/
relative_permalinks: true
exclude:
  - CNAME
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - node_modules/
  - package.json
  - Rakefile
  - README.md
  - vendor/

layouts: ./_noita

noita:
  name: Computational Systems Biology/Integrative Genomics
  description: INMEGEN
  author:
    name: Anatol Broder

    url: http://penibelst.de/
  lang: en
  favicons:
    - /images/logo.png
  topbar:
    toggle: Menu
    right:
      - name: Home
        url: /home/
      - name: About
        url: /about/
      - name: People
        url: /people/
      - name: Publications
        url: /publications/  
      - name: Blog
        url: /blog/
      - name: Contact
        url: /contact/
      - name: Repository
        url: https://github.com/penibelst/jekyll-noita
        class: small button

compress_html:
  clippings: [html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
